version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app:delegated,rw
      - backend_data:/home/finsc/media
    depends_on:
      - db
      - timescale

  timescale:
    platform: linux/x86_64
    image: timescale/timescaledb-ha:pg16
    command:
      - "postgres"
      - "-c"
      - "max_locks_per_transaction=1024"
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: fai
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: fai

  db:
    platform: linux/x86_64
    image: postgres:14.5-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: fai
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: fai

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    environment:
      - ADMINER_DESIGN=pepa-linha-dark

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongo:27017/
      ME_CONFIG_BASICAUTH: false

secrets:
   db_password:
     file: db_password.txt

volumes:
  db_data:
  backend_data:
