"""Alter userId in ChartConfig to string

Revision ID: 16082ec127b4
Revises: e88628045e66
Create Date: 2024-06-12 20:13:12.270476

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '16082ec127b4'
down_revision = 'e88628045e66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chartconfig', 'userId',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint('chartconfig_userId_key', 'chartconfig', type_='unique')
    op.create_index(op.f('ix_chartconfig_userId'), 'chartconfig', ['userId'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chartconfig_userId'), table_name='chartconfig')
    op.create_unique_constraint('chartconfig_userId_key', 'chartconfig', ['userId'])
    op.alter_column('chartconfig', 'userId',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
