"""Update unique key for IncomStatement TCA data

Revision ID: 1c4c3976ffe6
Revises: 92bc9ff2b182
Create Date: 2024-10-01 10:03:15.669962

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1c4c3976ffe6'
down_revision = '92bc9ff2b182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('symbol_yearly_income_statement', 'incomestatement', ['symbol', 'yearly'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('symbol_yearly_income_statement', 'incomestatement', type_='unique')
    # ### end Alembic commands ###
