"""Create StockPrice Table

Revision ID: 540eb9de9ff4
Revises: 5795d70b8d0c
Create Date: 2024-04-04 01:49:06.758026

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = '540eb9de9ff4'
down_revision = '5795d70b8d0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stockprice',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.TEXT(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('operation_income', sa.BigInteger(), nullable=True),
    )

    # PrimaryKey will prevent creating hypertable with TimescaleDB
    op.execute("SELECT create_hypertable('stockprice', by_range('time'));")
    op.create_index('ix_ticker_time', 'stockprice', ['symbol', text("time DESC")])
    op.execute("ALTER TABLE stockprice "
               "SET ("
               "timescaledb.compress,"
               " timescaledb.compress_segmentby='symbol',"
               " timescaledb.compress_orderby='time DESC');")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticker_time'), table_name='stockprice')
    op.drop_table('stockprice')
    # ### end Alembic commands ###
