"""Update unique key for BalanceSheet, Cashflow TCA data

Revision ID: 6b5c9d769eb3
Revises: 1c4c3976ffe6
Create Date: 2024-10-01 10:15:08.689498

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6b5c9d769eb3'
down_revision = '1c4c3976ffe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('symbol_yearly_balance_sheet', 'balancesheet', ['symbol', 'yearly'])
    op.create_unique_constraint('symbol_yearly_cashflow', 'cashflow', ['symbol', 'yearly'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('symbol_yearly_cashflow', 'cashflow', type_='unique')
    op.drop_constraint('symbol_yearly_balance_sheet', 'balancesheet', type_='unique')
    # ### end Alembic commands ###
