"""Generate Fincial Ratio Model

Revision ID: 74f90d2e3519
Revises: 6b5c9d769eb3
Create Date: 2025-01-23 05:01:11.354052

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '74f90d2e3519'
down_revision = '6b5c9d769eb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financialratio',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('yearly', sa.Boolean(), nullable=False),
    sa.Column('financial_ratio', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'yearly', name='symbol_yearly_financial_ratio')
    )
    op.create_index(op.f('ix_financialratio_symbol'), 'financialratio', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financialratio_symbol'), table_name='financialratio')
    op.drop_table('financialratio')
    # ### end Alembic commands ###
