"""Add TCA data

Revision ID: 92bc9ff2b182
Revises: a78f1f50ffe8
Create Date: 2024-10-01 09:44:24.129285

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '92bc9ff2b182'
down_revision = 'a78f1f50ffe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balancesheet',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('yearly', sa.Boolean(), nullable=False),
    sa.Column('balance_sheet', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balancesheet_symbol'), 'balancesheet', ['symbol'], unique=False)
    op.create_table('cashflow',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('yearly', sa.Boolean(), nullable=False),
    sa.Column('cashflow', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashflow_symbol'), 'cashflow', ['symbol'], unique=False)
    op.create_table('incomestatement',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('yearly', sa.Boolean(), nullable=False),
    sa.Column('income_statement', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incomestatement_symbol'), 'incomestatement', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incomestatement_symbol'), table_name='incomestatement')
    op.drop_table('incomestatement')
    op.drop_index(op.f('ix_cashflow_symbol'), table_name='cashflow')
    op.drop_table('cashflow')
    op.drop_index(op.f('ix_balancesheet_symbol'), table_name='balancesheet')
    op.drop_table('balancesheet')
    # ### end Alembic commands ###
