"""Remove relationship of Stock table temporarily

Revision ID: a78f1f50ffe8
Revises: f22148f32771
Create Date: 2024-09-15 03:28:26.621368

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a78f1f50ffe8'
down_revision = 'f22148f32771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_listed_date', table_name='stock')
    op.drop_constraint('stock_sector_id_fkey', 'stock', type_='foreignkey')
    op.drop_constraint('stock_floor_id_fkey', 'stock', type_='foreignkey')
    op.drop_constraint('stock_industry_id_fkey', 'stock', type_='foreignkey')
    op.drop_constraint('stock_group_id_fkey', 'stock', type_='foreignkey')
    op.drop_constraint('stock_type_id_fkey', 'stock', type_='foreignkey')
    op.drop_column('stock', 'industry_id')
    op.drop_column('stock', 'type_id')
    op.drop_column('stock', 'is_listed')
    op.drop_column('stock', 'listed_date')
    op.drop_column('stock', 'group_id')
    op.drop_column('stock', 'logo')
    op.drop_column('stock', 'floor_id')
    op.drop_column('stock', 'sector_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('sector_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('stock', sa.Column('floor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('stock', sa.Column('logo', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('stock', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('stock', sa.Column('listed_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('stock', sa.Column('is_listed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('stock', sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('stock', sa.Column('industry_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('stock_type_id_fkey', 'stock', 'stocktype', ['type_id'], ['id'])
    op.create_foreign_key('stock_group_id_fkey', 'stock', 'stockgroup', ['group_id'], ['id'])
    op.create_foreign_key('stock_industry_id_fkey', 'stock', 'industry', ['industry_id'], ['id'])
    op.create_foreign_key('stock_floor_id_fkey', 'stock', 'stockfloor', ['floor_id'], ['id'])
    op.create_foreign_key('stock_sector_id_fkey', 'stock', 'sector', ['sector_id'], ['id'])
    op.create_index('ix_stock_listed_date', 'stock', ['listed_date'], unique=False)
    # ### end Alembic commands ###
