"""Update ChartConfig Model

Revision ID: e88628045e66
Revises: 439f700eda98
Create Date: 2024-06-05 19:15:51.628568

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e88628045e66'
down_revision = '439f700eda98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chartconfig', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('chartconfig', sa.Column('userId', sa.UUID(), nullable=False))
    op.add_column('chartconfig', sa.Column('resolution', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('chartconfig', sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('chartconfig', sa.Column('content', sa.JSON(), nullable=False))
    op.drop_constraint('chartconfig_user_id_key', 'chartconfig', type_='unique')
    op.create_unique_constraint(None, 'chartconfig', ['userId'])
    op.drop_column('chartconfig', 'config')
    op.drop_column('chartconfig', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chartconfig', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('chartconfig', sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chartconfig', type_='unique')
    op.create_unique_constraint('chartconfig_user_id_key', 'chartconfig', ['user_id'])
    op.drop_column('chartconfig', 'content')
    op.drop_column('chartconfig', 'symbol')
    op.drop_column('chartconfig', 'resolution')
    op.drop_column('chartconfig', 'userId')
    op.drop_column('chartconfig', 'name')
    # ### end Alembic commands ###
